openapi: 3.0.0
info:
  title: Security Copilot Email
  description: Sends an HTML-formatted security investigation report via email using an Azure Logic App.
  version: 1.0.0

servers:
  - url: https://prod-06.australiaeast.logic.azure.com:443/workflows/6b91d727d88d4e0b8887e3137c4a96ea/triggers/manual/paths/invoke
  #https://prod-31.australiaeast.logic.azure.com:443/workflows/bf5f0331504e4fe79607ad3769190073/triggers/manual/paths/invoke
  #https://prod-06.australiaeast.logic.azure.com:443/workflows/6b91d727d88d4e0b8887e3137c4a96ea/triggers/manual/paths/invoke

paths:
  /:
    post:
      operationId: Securitycopilotemail
      summary: Send Security Copilot Email
      description: Sends an HTML report via Logic App. Requires To, Subject, Message.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required: [To, Subject, Message]
              properties:
                To: { type: string }
                Subject: { type: string }
                Message: { type: string }
                CaseOutput: { type: string }
                IncidentID: { type: string }
      responses:
        "200": { description: Email sent successfully. }
        "500": { description: Failed to send email. }
